const ALL_DETAILS = {
  information_Technology: [
    { id: 1, title: "Artificial Intelligence Engineer", path: "/ai-engineer" },
    { id: 2, title: "Augmented Reality Engineer", path: "/ar-engineer" },
    { id: 3, title: "Big Data Analyst", path: "/big-data-analyst" },
    { id: 4, title: "Blockchain Developer", path: "/blockchain-developer" },
    { id: 5, title: "Cloud Engineer", path: "/cloud-engineer" },
    { id: 6, title: "Computer Hardware Engineer", path: "/hardware-engineer" },
    { id: 7, title: "Computer Network Architect", path: "/network-architect" },
    { id: 8, title: "Computer Science Engineer", path: "/cs-engineer" },
    { id: 9, title: "Computer Scientist", path: "/computer-scientist" },
    {
      id: 10,
      title: "Cyber Security Specialist",
      path: "/cyber-security-specialist",
    },
    { id: 11, title: "Data Scientist", path: "/data-scientist" },
    { id: 12, title: "Database Administrator", path: "/database-admin" },
    { id: 13, title: "Full Stack Developer", path: "/full-stack-developer" },
    { id: 14, title: "Game Designer and Developer", path: "/game-designer" },
    {
      id: 15,
      title: "Geo-Informatics Engineer",
      path: "/geo-informatics-engineer",
    },
    { id: 16, title: "Help Desk Analyst", path: "/help-desk-analyst" },
    { id: 17, title: "Information Technology Engineer", path: "/it-engineer" },
    {
      id: 18,
      title: "Internet of Things (IoT) Solutions Architect",
      path: "/iot-architect",
    },
    { id: 19, title: "Network Administrator", path: "/network-administrator" },
    {
      id: 20,
      title: "Programmer/Coder/Software Engineer",
      path: "/software-engineer",
    },
    { id: 21, title: "SEO Manager", path: "/seo-manager" },
    { id: 22, title: "Software Application Packager", path: "/app-packager" },
    { id: 23, title: "Systems Analyst", path: "/systems-analyst" },
    { id: 24, title: "User Experience Designer", path: "/ux-designer" },
    { id: 25, title: "Virtual Reality Engineer", path: "/vr-engineer" },
    { id: 26, title: "Web Analyst", path: "/web-analyst" },
    { id: 27, title: "Web Designer", path: "/web-designer" },
  ],
  Engineering: [
    { id: 28, title: "Aeronautical Engineer", path: "/aeronautical-engineer" },
    { id: 29, title: "Automobile Engineer", path: "/automobile-engineer" },
    {
      id: 30,
      title: "Bioinformatics Engineering",
      path: "/bioinformatics-engineering",
    },
    { id: 31, title: "Biomedical Engineer", path: "/biomedical-engineer" },
    {
      id: 32,
      title: "Biotechnology Engineer",
      path: "/biotechnology-engineer",
    },
    { id: 33, title: "Broadcast Engineer", path: "/broadcast-engineer" },
    {
      id: 34,
      title: "CAD Designer for Carpets",
      path: "/cad-designer-carpets",
    },
    {
      id: 35,
      title: "CAD Jewellery Designer",
      path: "/cad-jewellery-designer",
    },
    {
      id: 36,
      title: "Ceramic Technologist/Engineer",
      path: "/ceramic-technologist",
    },
    { id: 37, title: "Chemical Engineer", path: "/chemical-engineer" },
    {
      id: 38,
      title: "Civil Engineer/Structural Engineer",
      path: "/civil-engineer",
    },
    { id: 39, title: "Corrosion Engineer", path: "/corrosion-engineer" },
    { id: 40, title: "Design Engineer", path: "/design-engineer" },
    {
      id: 41,
      title: "Development Operations Engineer",
      path: "/dev-ops-engineer",
    },
    {
      id: 42,
      title: "Electrical and Electronics Engineer",
      path: "/electrical-electronics-engineer",
    },
    {
      id: 43,
      title: "Electronics Designer/VLSI/Embedded System Designer",
      path: "/electronics-vlsi-designer",
    },
    {
      id: 44,
      title: "Electronics and Communication Engineer",
      path: "/electronics-communication-engineer",
    },
    {
      id: 45,
      title: "Environmental Engineer",
      path: "/environmental-engineer",
    },
    {
      id: 46,
      title: "Fire and Safety Engineer",
      path: "/fire-safety-engineer",
    },
    { id: 47, title: "Food Engineer", path: "/food-engineer" },
    { id: 48, title: "Footwear Designer", path: "/footwear-designer" },
    { id: 49, title: "Forensic Engineer", path: "/forensic-engineer" },
    {
      id: 50,
      title: "Geo-Informatics Engineer",
      path: "/geo-informatics-engineer",
    },
    { id: 51, title: "Graphics Designer", path: "/graphics-designer" },
    { id: 52, title: "Industrial Designer", path: "/industrial-designer" },
    { id: 53, title: "Industrial Engineer", path: "/industrial-engineer" },
    {
      id: 54,
      title: "Instrumentation Engineer",
      path: "/instrumentation-engineer",
    },
    {
      id: 55,
      title: "Manufacturing Engineer",
      path: "/manufacturing-engineer",
    },
    { id: 56, title: "Marine Engineer", path: "/marine-engineer" },
    { id: 57, title: "Mechanical Engineer", path: "/mechanical-engineer" },
    { id: 58, title: "Metallurgy Engineer", path: "/metallurgy-engineer" },
    { id: 59, title: "Mining Engineer", path: "/mining-engineer" },
    {
      id: 60,
      title: "Nanotechnology/Nanoscience Engineer",
      path: "/nanotechnology-engineer",
    },
    { id: 61, title: "Optical Engineer", path: "/optical-engineer" },
    { id: 62, title: "Petroleum Engineer", path: "/petroleum-engineer" },
    {
      id: 63,
      title: "Pharmaceutical Engineer",
      path: "/pharmaceutical-engineer",
    },
    {
      id: 64,
      title: "Printing Engineer/Technologist",
      path: "/printing-engineer",
    },
    { id: 65, title: "Process Engineer", path: "/process-engineer" },
    { id: 66, title: "Product Designer", path: "/product-designer" },
    {
      id: 67,
      title: "Quality Assurance Engineer",
      path: "/quality-assurance-engineer",
    },
    { id: 68, title: "Railway Engineer", path: "/railway-engineer" },
    { id: 69, title: "Robotics Engineer", path: "/robotics-engineer" },
    { id: 70, title: "Sales Engineer", path: "/sales-engineer" },
    {
      id: 71,
      title: "Smart Manufacturing and Automation Engineering",
      path: "/smart-manufacturing-engineer",
    },
    { id: 72, title: "Sound Engineer", path: "/sound-engineer" },
    { id: 73, title: "Textile Engineer", path: "/textile-engineer" },
    { id: 74, title: "Tool Engineer", path: "/tool-engineer" },
    {
      id: 75,
      title: "Water Resource Engineer",
      path: "/water-resource-engineer",
    },
  ],
  GovernmentServices: [
    { id: 76, title: "Agniveer", path: "/agniveer" },
    { id: 77, title: "Border Security Force (BSF)", path: "/bsf" },
    { id: 78, title: "CISF Officer", path: "/cisf-officer" },
    { id: 79, title: "Coast Guard", path: "/coast-guard" },
    { id: 80, title: "CRPF Officer", path: "/crpf-officer" },
    { id: 81, title: "Customs Officer", path: "/customs-officer" },
    { id: 82, title: "FSSAI Officer", path: "/fssai-officer" },
    { id: 83, title: "Gramin Dak Sevak", path: "/gramin-dak-sevak" },
    { id: 84, title: "Indian Administrative Service", path: "/ias" },
    {
      id: 85,
      title: "Indian Air Force Officer",
      path: "/indian-air-force-officer",
    },
    { id: 86, title: "Indian Army Officer", path: "/indian-army-officer" },
    { id: 87, title: "Indian Foreign Service", path: "/ifs" },
    { id: 88, title: "Indian Forest Service", path: "/ifs-forest-service" },
    { id: 89, title: "Indian Home Guard", path: "/indian-home-guard" },
    { id: 90, title: "Indian Navy Officer", path: "/indian-navy-officer" },
    { id: 91, title: "Indian Police Service", path: "/ips" },
    {
      id: 92,
      title: "Indian Railway Accounts Service",
      path: "/indian-railway-accounts-service",
    },
    {
      id: 93,
      title: "Indian Railway Service of Electrical Engineers",
      path: "/indian-railway-electrical-engineers",
    },
    {
      id: 94,
      title: "Indian Railway Personnel Service",
      path: "/indian-railway-personnel-service",
    },
    {
      id: 95,
      title: "Indian Railway Service of Engineers",
      path: "/indian-railway-engineers",
    },
    {
      id: 96,
      title: "Indian Railway Service of Mechanical Engineers",
      path: "/indian-railway-mechanical-engineers",
    },
    {
      id: 97,
      title: "Indian Railway Service of Signal Engineers",
      path: "/indian-railway-signal-engineers",
    },
    {
      id: 98,
      title: "Indian Railway Stores Service (IRSS)",
      path: "/indian-railways-stores-service",
    },
    {
      id: 99,
      title: "Indian Railways Traffic Service (IRTS)",
      path: "/indian-railways-traffic-service",
    },
    {
      id: 100,
      title: "Indian Revenue Service",
      path: "/indian-revenue-service",
    },
    { id: 101, title: "ITBP Officer", path: "/itbp-officer" },
    {
      id: 102,
      title: "Inspector of Income Tax",
      path: "/inspector-income-tax",
    },
    { id: 103, title: "Loco Pilot", path: "/loco-pilot" },
    { id: 104, title: "Merchant Navy", path: "/merchant-navy" },
    { id: 105, title: "Police Constable", path: "/police-constable" },
    {
      id: 106,
      title: "Railway Protection Force (RPF)",
      path: "/railway-protection-force",
    },
    { id: 107, title: "SSB-Sashastra Seema Bal Officer", path: "/ssb-officer" },
    {
      id: 108,
      title: "Sub-inspector of Police",
      path: "/sub-inspector-of-police",
    },
  ],
  Management: [
    {
      id: 142,
      title: "Assistant Catering Manager",
      path: "/assistant-catering-manager",
    },
    { id: 143, title: "BPO Executive", path: "/bpo-executive" },
    { id: 144, title: "Event Manager", path: "/event-manager" },
    {
      id: 145,
      title: "Human Resource Manager",
      path: "/human-resource-manager",
    },
    { id: 146, title: "Inventory Manager", path: "/inventory-manager" },
    {
      id: 147,
      title: "Knowledge Process Outsourcing Executive",
      path: "/kpo-executive",
    },
    {
      id: 148,
      title: "Purchasing and Materials Manager",
      path: "/purchasing-materials-manager",
    },
    {
      id: 149,
      title: "Quality Assurance Manager",
      path: "/quality-assurance-manager",
    },
    { id: 150, title: "Retail Manager", path: "/retail-manager" },
    {
      id: 151,
      title: "Rural Development Specialist/Manager",
      path: "/rural-development-manager",
    },
    {
      id: 152,
      title: "Sales and Marketing Manager",
      path: "/sales-marketing-manager",
    },
    { id: 153, title: "Sports Agent/Manager", path: "/sports-agent-manager" },
    {
      id: 154,
      title: "Sports Equipment Manager",
      path: "/sports-equipment-manager",
    },
  ],
  OperationsLogisticsAndHospitality: [
    { id: 155, title: "Aircraft Pilot", path: "/aircraft-pilot" },
    { id: 156, title: "Air Hostess/Purser", path: "/air-hostess-purser" },
    {
      id: 157,
      title: "Airline Cargo Assistant",
      path: "/airline-cargo-assistant",
    },
    {
      id: 158,
      title: "Airline Customer Service Executive",
      path: "/airline-customer-service-executive",
    },
    {
      id: 159,
      title: "Airline Ground Support Equipment Operator",
      path: "/airline-ground-support-equipment-operator",
    },
    {
      id: 160,
      title: "Air Traffic Controller",
      path: "/air-traffic-controller",
    },
    { id: 161, title: "Auctioneer", path: "/auctioneer" },
    { id: 162, title: "Bartender/Mixologist", path: "/bartender-mixologist" },
    { id: 163, title: "Bulldozer Operator", path: "/bulldozer-operator" },
    {
      id: 164,
      title: "Cold Chain Process Management Specialist",
      path: "/cold-chain-process-management-specialist",
    },
    { id: 165, title: "Commercial Driver", path: "/commercial-driver" },
    {
      id: 166,
      title: "Conveyor Operation and Maintenance Technician",
      path: "/conveyor-operation-maintenance-technician",
    },
    { id: 167, title: "Distribution Manager", path: "/distribution-manager" },
    {
      id: 168,
      title: "Food and Beverage Manager",
      path: "/food-beverage-manager",
    },
    {
      id: 169,
      title: "Front Office Associate",
      path: "/front-office-associate",
    },
    { id: 170, title: "Logistics Analyst", path: "/logistics-analyst" },
    { id: 171, title: "Logistics Manager", path: "/logistics-manager" },
    { id: 172, title: "Multi-Tasking Staff", path: "/multi-tasking-staff" },
    { id: 173, title: "Nature Guide", path: "/nature-guide" },
    { id: 174, title: "Office Administrator", path: "/office-administrator" },
    { id: 175, title: "Operations Manager", path: "/operations-manager" },
    {
      id: 176,
      title: "Package Dyeing Machine Operator",
      path: "/package-dyeing-machine-operator",
    },
    {
      id: 177,
      title: "Port Operations Manager",
      path: "/port-operations-manager",
    },
    {
      id: 178,
      title: "Secretary/Personal Assistant",
      path: "/secretary-personal-assistant",
    },
    { id: 179, title: "Sommelier", path: "/sommelier" },
    { id: 180, title: "Supply Chain Manager", path: "/supply-chain-manager" },
    { id: 181, title: "Tour Guide", path: "/tour-guide" },
    { id: 182, title: "Tour Operator", path: "/tour-operator" },
    {
      id: 183,
      title: "Transportation Manager",
      path: "/transportation-manager",
    },
    { id: 184, title: "Travel Consultant", path: "/travel-consultant" },
    { id: 185, title: "Urban Planner", path: "/urban-planner" },
  ],
  PublicPolicyLawAndSafety: [
    { id: 186, title: "Arbitrator", path: "/arbitrator" },
    {
      id: 187,
      title: "Corporate Legal Advisor/Compliance Officer",
      path: "/corporate-legal-advisor",
    },
    { id: 188, title: "Detective", path: "/detective" },
    { id: 189, title: "Fire Fighter", path: "/fire-fighter" },
    { id: 190, title: "Human Rights Lawyer", path: "/human-rights-lawyer" },
    {
      id: 191,
      title: "International Relations Specialist",
      path: "/international-relations-specialist",
    },
    { id: 192, title: "Judge", path: "/judge" },
    {
      id: 193,
      title: "Lawyer/Law Officer/Advocate",
      path: "/lawyer-law-officer-advocate",
    },
    { id: 194, title: "Medico Legal Advisor", path: "/medico-legal-advisor" },
    { id: 195, title: "Patent Lawyer", path: "/patent-lawyer" },
    { id: 196, title: "Psephologist", path: "/psephologist" },
    { id: 197, title: "Public Policy Advisor", path: "/public-policy-advisor" },
    { id: 198, title: "Social Worker", path: "/social-worker" },
    { id: 199, title: "Sports Lawyer", path: "/sports-lawyer" },
    {
      id: 200,
      title: "Unarmed Security Guard",
      path: "/unarmed-security-guard",
    },
  ],
  ResearchAndDevelopment: [
    { id: 201, title: "Anthropologist", path: "/anthropologist" },
    { id: 202, title: "Archaeologist", path: "/archaeologist" },
    { id: 203, title: "Archivist", path: "/archivist" },
    { id: 204, title: "Astrophysicist", path: "/astrophysicist" },
    { id: 205, title: "Bacteriologist", path: "/bacteriologist" },
    { id: 206, title: "Botanist", path: "/botanist" },
    {
      id: 207,
      title: "Child Development Specialist",
      path: "/child-development-specialist",
    },
    { id: 208, title: "Criminologist", path: "/criminologist" },
    { id: 209, title: "Curator", path: "/curator" },
    {
      id: 210,
      title: "Cytologist/Cytotechnologist",
      path: "/cytologist-cytotechnologist",
    },
    {
      id: 211,
      title: "Data Collector or Field Surveyor Enumerator",
      path: "/data-collector-field-surveyor-enumerator",
    },
    { id: 212, title: "Demographer", path: "/demographer" },
    { id: 213, title: "Ecologist", path: "/ecologist" },
    { id: 214, title: "Economist", path: "/economist" },
    { id: 215, title: "Engineering Physicist", path: "/engineering-physicist" },
    {
      id: 216,
      title: "English Literature Scholar",
      path: "/english-literature-scholar",
    },
    { id: 217, title: "Epigraphist", path: "/epigraphist" },
    { id: 218, title: "Forensic Scientist", path: "/forensic-scientist" },
    { id: 219, title: "Genetic Engineer", path: "/genetic-engineer" },
    { id: 220, title: "Geographer", path: "/geographer" },
    { id: 221, title: "Geologist", path: "/geologist" },
    { id: 222, title: "Historian", path: "/historian" },
    { id: 223, title: "Mathematician", path: "/mathematician" },
    { id: 224, title: "Meteorologist", path: "/meteorologist" },
    { id: 225, title: "Museologist", path: "/museologist" },
    { id: 226, title: "Nano Scientist", path: "/nano-scientist" },
    { id: 227, title: "Paleontologist", path: "/paleontologist" },
    { id: 228, title: "Physicist", path: "/physicist" },
    { id: 229, title: "Political Scientist", path: "/political-scientist" },
    {
      id: 230,
      title: "Scientific Assistant (IMD)",
      path: "/scientific-assistant-imd",
    },
    { id: 231, title: "Seismologist", path: "/seismologist" },
    { id: 232, title: "Sociologist", path: "/sociologist" },
    { id: 233, title: "Space Scientist", path: "/space-scientist" },
    { id: 234, title: "Statistician", path: "/statistician" },
    { id: 235, title: "Toxicologist", path: "/toxicologist" },
    { id: 236, title: "Virologist", path: "/virologist" },
    { id: 237, title: "Zoologist", path: "/zoologist" },
  ],
  TechnicalAndSkillTrades: [
    { id: 238, title: "Applique Artisan", path: "/applique-artisan" },
    {
      id: 239,
      title: "Assistant Beauty Therapist",
      path: "/assistant-beauty-therapist",
    },
    {
      id: 240,
      title: "Assistant Carpenter—Wooden Furniture",
      path: "/assistant-carpenter-wooden-furniture",
    },
    {
      id: 241,
      title: "Assistant False Ceiling and Drywall Installer",
      path: "/assistant-false-ceiling-drywall-installer",
    },
    {
      id: 242,
      title: "Assistant Fitter: Levelling, Alignment and Balancing",
      path: "/assistant-fitter-levelling-alignment-balancing",
    },
    {
      id: 243,
      title: "Assistant Hair Stylist",
      path: "/assistant-hair-stylist",
    },
    { id: 244, title: "Assistant Surveyor", path: "/assistant-surveyor" },
    {
      id: 245,
      title: "Auto/E-Rickshaw Driver and Technician",
      path: "/auto-e-rickshaw-driver-technician",
    },
    {
      id: 246,
      title: "Automotive Electrician",
      path: "/automotive-electrician",
    },
    {
      id: 247,
      title: "Auto Service Technician Level 3",
      path: "/auto-service-technician-level-3",
    },
    { id: 248, title: "Bamboo Mat Weaver", path: "/bamboo-mat-weaver" },
    {
      id: 249,
      title: "Bamboo Utility Product Tailor",
      path: "/bamboo-utility-product-tailor",
    },
    {
      id: 250,
      title: "Operator-Boring Machine",
      path: "/operator-boring-machine",
    },
    { id: 251, title: "Cake Artist", path: "/cake-artist" },
    { id: 252, title: "Camp Helper", path: "/camp-helper" },
    {
      id: 253,
      title: "CCTV Installation Technician",
      path: "/cctv-installation-technician",
    },
    { id: 254, title: "Chef", path: "/chef" },
    {
      id: 255,
      title: "Child Caretaker (Non-clinical)",
      path: "/child-caretaker-non-clinical",
    },
    { id: 256, title: "Chocolatier", path: "/chocolatier" },
    { id: 257, title: "CNC Operator Turning", path: "/cnc-operator-turning" },
    {
      id: 258,
      title: "Coffee Taster/Barrista/Q Grader",
      path: "/coffee-taster-barrista-q-grader",
    },
    {
      id: 259,
      title: "Conveyor Operation and Maintenance Technician",
      path: "/conveyor-operation-maintenance-technician",
    },
    {
      id: 260,
      title: "Crochet Lacemaker – Furnishings",
      path: "/crochet-lacemaker-furnishings",
    },
    { id: 261, title: "Doors and Windows Fixer", path: "/doors-windows-fixer" },
    { id: 262, title: "Draughtsman", path: "/draughtsman" },
    {
      id: 263,
      title:
        "DTH Set Top Box Installation and Service Technician (Cable TV Operator)",
      path: "/dth-set-top-box-installation-service-technician",
    },
    {
      id: 264,
      title: "Electric Vehicle Assembly Technician",
      path: "/electric-vehicle-assembly-technician",
    },
    { id: 265, title: "Electrician (General)", path: "/electrician-general" },
    { id: 266, title: "E-waste Collector", path: "/e-waste-collector" },
    {
      id: 267,
      title: "Field Technician – Other Home Appliances",
      path: "/field-technician-other-home-appliances",
    },
    {
      id: 268,
      title: "Fitter–Electrical and Electronic Assembly",
      path: "/fitter-electrical-electronic-assembly",
    },
    { id: 269, title: "Fitter–Fabrication", path: "/fitter-fabrication" },
    {
      id: 270,
      title: "Fitter–Mechanical Assembly",
      path: "/fitter-mechanical-assembly",
    },
    { id: 271, title: "Fitter–Processing", path: "/fitter-processing" },
    {
      id: 272,
      title: "Food and Beverage Service-Steward",
      path: "/food-beverage-service-steward",
    },
    { id: 273, title: "General Housekeeper", path: "/general-housekeeper" },
    {
      id: 274,
      title: "Helper–Shuttering Carpenter",
      path: "/helper-shuttering-carpenter",
    },
    { id: 275, title: "Helper–Fabrication", path: "/helper-fabrication" },
    { id: 276, title: "Homecook", path: "/homecook" },
    { id: 277, title: "Home Delivery Boy", path: "/home-delivery-boy" },
    {
      id: 278,
      title: "Housekeeping Attendant (Manual Cleaning)",
      path: "/housekeeping-attendant-manual-cleaning",
    },
    {
      id: 279,
      title: "Industrial Production Worker – Food Processing",
      path: "/industrial-production-worker-food-processing",
    },
    {
      id: 280,
      title: "Installer – Frameless Glass Doors/Windows",
      path: "/installer-frameless-glass-doors-windows",
    },
    { id: 281, title: "Jute Handloom Weaver", path: "/jute-handloom-weaver" },
    { id: 282, title: "Kitchen Steward", path: "/kitchen-steward" },
    { id: 283, title: "Lapidarist", path: "/lapidarist" },
    { id: 284, title: "Leather Technologist", path: "/leather-technologist" },
    {
      id: 285,
      title: "Light Vehicle Driver (LMV)",
      path: "/light-vehicle-driver-lmv",
    },
    { id: 286, title: "Mason (General)", path: "/mason-general" },
    { id: 287, title: "Mason (Stone)", path: "/mason-stone" },
    { id: 288, title: "Mason (Tiling)", path: "/mason-tiling" },
    {
      id: 289,
      title: "Master Hand Embroiderer (Hand Crafted Textiles)",
      path: "/master-hand-embroiderer",
    },
    { id: 290, title: "Mechanical Fitter", path: "/mechanical-fitter" },
    {
      id: 291,
      title: "Multi-skill Technician (Electrical)",
      path: "/multi-skill-technician-electrical",
    },
    {
      id: 292,
      title: "Multi-skill Technician (Food Processing)",
      path: "/multi-skill-technician-food-processing",
    },
    { id: 293, title: "Oil Technologist", path: "/oil-technologist" },
    {
      id: 294,
      title: "Construction Painter and Decorator",
      path: "/construction-painter-decorator",
    },
    { id: 295, title: "Pastry Chef", path: "/pastry-chef" },
    { id: 296, title: "Plumber", path: "/plumber" },
    {
      id: 297,
      title: "Refrigeration Technician",
      path: "/refrigeration-technician",
    },
    { id: 298, title: "Retail Cashier", path: "/retail-cashier" },
    {
      id: 299,
      title: "Retail Store Operations Assistant",
      path: "/retail-store-operations-assistant",
    },
    { id: 300, title: "Room Attendant", path: "/room-attendant" },
    { id: 301, title: "Rubber Technologist", path: "/rubber-technologist" },
    {
      id: 302,
      title: "Self-employed E-tailer",
      path: "/self-employed-e-tailer",
    },
    {
      id: 303,
      title: "Sewing Machine Operator",
      path: "/sewing-machine-operator",
    },
    { id: 304, title: "Showroom Hostess/Host", path: "/showroom-hostess-host" },
    {
      id: 305,
      title: "Smartphone Repair Technician",
      path: "/smartphone-repair-technician",
    },
    {
      id: 306,
      title: "Solar and LED Technician",
      path: "/solar-led-technician",
    },
    { id: 307, title: "Spa Therapist", path: "/spa-therapist" },
    {
      id: 308,
      title: "Stonecutter (Cutting Machine Operator) – Stone Craft",
      path: "/stonecutter-stone-craft",
    },
    {
      id: 309,
      title: "Storekeeper – Construction",
      path: "/storekeeper-construction",
    },
    {
      id: 310,
      title: "Stringing/Beading Artist (Fashion Jewellery)",
      path: "/stringing-beading-artist-fashion-jewellery",
    },
    { id: 311, title: "Sugar Technologist", path: "/sugar-technologist" },
    { id: 312, title: "Tea Taster", path: "/tea-taster" },
    { id: 313, title: "Tour Operator", path: "/tour-operator" },
    { id: 314, title: "Tower Technician", path: "/tower-technician" },
    {
      id: 315,
      title: "Trainee Chef/Assistant Cook",
      path: "/trainee-chef-assistant-cook",
    },
    { id: 316, title: "Waste Collector", path: "/waste-collector" },
    { id: 317, title: "Wood Polisher", path: "/wood-polisher" },
  ],
};

const ALL_CATEGORIES = [
  {
    id: 1,
    title: "Information Technology",
    path: "/information-technology",
  },
  {
    id: 2,
    title: "Engineering",
    path: "/engineering",
  },
  {
    id: 3,
    title: "Government Services",
    path: "/government-services",
  },
  {
    id: 4,
    title: "Management",
    path: "/management",
  },
  {
    id: 5,
    title: "Operations Logistics And Hospitality",
    path: "/operations-logistics-hospitality",
  },
  {
    id: 6,
    title: "Public Policy Law And Safety",
    path: "/public-policy-law-safety",
  },
  {
    id: 7,
    title: "Research And Development",
    path: "/research-development",
  },
  {
    id: 8,
    title: "Technical And Skill Trades",
    path: "/technical-skill-trades",
  },
];

module.exports = {
  ALL_DETAILS,
  ALL_CATEGORIES,
};
